Repository HDFGroup/hsds, pull requests merged in 2024-06, with the labels that each got.

#373 fixes for quick start usage
  README.md
  build.sh
  tests/integ/config.py
Labels: bug, enhancement

#377 Prevent use of new major numpy version
  pyproject.toml
  requirements.txt
Labels: ci/cd, dependencies

#380 Restrict numpy version in Pipfile
  Pipfile
Labels: dependencies
